version: '3.7'

services: 
  app:
    build: .
    container_name: resync-assignment
    environment:
      PORT: 8080
    ports:
      - 8080:8080
    volumes: 
      - ./app:/app
      - app/node_modules
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

  mysqldb:
    image: mysql:8.0.2
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: resync
      MYSQL_ROOT_PASSWORD: jainamit6@    
    ports:
        - "3306"
